import type { ScheduleItem } from "./api";

/**
 * Grade Oficial da Programação do COPOL 2026 (05/11 a 07/11).
 * Total de 34 atividades oficiais cadastradas:
 * - 05/11 (Quinta-feira): 14 itens
 * - 06/11 (Sexta-feira): 15 itens
 * - 07/11 (Sábado): 5 itens
 *
 * Utilizado como fallback de contingência e renderização estática offline.
 */
export const COPOL_FALLBACK_SCHEDULE: ScheduleItem[] = [
  // ==========================================
  // QUINTA-FEIRA — 05/11/2026 (14 atividades)
  // ==========================================
  {
    id: "copol-day1-01",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "08:30",
    endTime: "09:00",
    title: "Credenciamento – Retirada de Crachás",
    speaker: null,
    location: "Foyer Principal",
    description: "Credenciamento – Retirada de Crachás",
    type: "Credenciamento",
    order: 0,
  },
  {
    id: "copol-day1-02",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "09:00",
    endTime: "10:00",
    title: "Cerimônia de Abertura – Coquetel de Boas-Vindas",
    speaker: null,
    location: "Auditório Principal",
    description: "Cerimônia de Abertura – Coquetel de Boas-Vindas",
    type: "Solenidade",
    order: 1,
  },
  {
    id: "copol-day1-03",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "10:00",
    endTime: "11:00",
    title: "Cristina Miura – Lucratividade para Recém-Formados",
    speaker: "Cristina Miura",
    location: "Auditório Principal",
    description: "Cristina Miura – Lucratividade para Recém-Formados",
    type: "Palestra",
    order: 2,
  },
  {
    id: "copol-day1-04",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "11:00",
    endTime: "12:00",
    title: "Prof. Dr. Letícia Lang – Odontologia Oncológica: o que o clínico precisa saber",
    speaker: "Prof. Dr. Letícia Lang",
    location: "Auditório Principal",
    description: "Prof. Dr. Letícia Lang – Odontologia Oncológica: o que o clínico precisa saber",
    type: "Palestra",
    order: 3,
  },
  {
    id: "copol-day1-05",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "12:00",
    endTime: "14:00",
    title: "Almoço",
    speaker: null,
    location: "Praça de Alimentação",
    description: "Almoço",
    type: "Intervalo",
    order: 4,
  },
  {
    id: "copol-day1-06",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "14:00",
    endTime: "15:00",
    title: "Hands On Carlos e Romanini",
    speaker: "Carlos e Romanini",
    location: "Sala Hands On 1",
    description: "Hands On Carlos e Romanini",
    type: "Hands On",
    order: 5,
  },
  {
    id: "copol-day1-07",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "15:00",
    endTime: "16:00",
    title: "Hands On Integrale",
    speaker: "Integrale",
    location: "Sala Hands On 2",
    description: "Hands On Integrale",
    type: "Hands On",
    order: 6,
  },
  {
    id: "copol-day1-08",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "16:00",
    endTime: "17:00",
    title: "Hands On Marcos Guskuma",
    speaker: "Marcos Guskuma",
    location: "Sala Hands On 1",
    description: "Hands On Marcos Guskuma",
    type: "Hands On",
    order: 7,
  },
  {
    id: "copol-day1-09",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "17:00",
    endTime: "18:00",
    title: "Hands On Marcela Clareamento",
    speaker: "Marcela",
    location: "Sala Hands On 2",
    description: "Hands On Marcela Clareamento",
    type: "Hands On",
    order: 8,
  },
  {
    id: "copol-day1-10",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "18:00",
    endTime: "19:00",
    title: "Coffee Break",
    speaker: null,
    location: "Área de Convivência",
    description: "Coffee Break",
    type: "Intervalo",
    order: 9,
  },
  {
    id: "copol-day1-11",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "19:00",
    endTime: "19:15",
    title: "Credenciamento – Retirada de Crachás",
    speaker: null,
    location: "Foyer Principal",
    description: "Credenciamento – Retirada de Crachás",
    type: "Credenciamento",
    order: 10,
  },
  {
    id: "copol-day1-12",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "19:15",
    endTime: "20:15",
    title: "Dra. Lázara – Palestra",
    speaker: "Dra. Lázara",
    location: "Auditório Principal",
    description: "Dra. Lázara – Palestra",
    type: "Palestra",
    order: 11,
  },
  {
    id: "copol-day1-13",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "20:15",
    endTime: "21:00",
    title: "Carlos Augusto – DTM",
    speaker: "Carlos Augusto",
    location: "Auditório Principal",
    description: "Carlos Augusto – DTM",
    type: "Palestra",
    order: 12,
  },
  {
    id: "copol-day1-14",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "20:15",
    endTime: "21:00",
    title: "Coquetel de Encerramento Dia 1",
    speaker: null,
    location: "Área de Convivência",
    description: "Coquetel de Encerramento Dia 1",
    type: "Solenidade",
    order: 13,
  },

  // ==========================================
  // SEXTA-FEIRA — 06/11/2026 (15 atividades)
  // ==========================================
  {
    id: "copol-day2-01",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "08:00",
    endTime: "08:30",
    title: "Recepção com DJ",
    speaker: null,
    location: "Foyer / Entrada",
    description: "Recepção com DJ",
    type: "Intervalo",
    order: 14,
  },
  {
    id: "copol-day2-02",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "08:30",
    endTime: "09:30",
    title: "Franciele Covalti – Tema a decidir",
    speaker: "Franciele Covalti",
    location: "Auditório Principal",
    description: "Franciele Covalti – Tema a decidir",
    type: "Palestra",
    order: 15,
  },
  {
    id: "copol-day2-03",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "09:30",
    endTime: "10:00",
    title: "Coffee Break",
    speaker: null,
    location: "Área de Convivência",
    description: "Coffee Break",
    type: "Intervalo",
    order: 16,
  },
  {
    id: "copol-day2-04",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "10:00",
    endTime: "11:00",
    title: "Dr. Giuliano Cesar – Periodontia",
    speaker: "Dr. Giuliano Cesar",
    location: "Auditório Principal",
    description: "Dr. Giuliano Cesar – Periodontia",
    type: "Palestra",
    order: 17,
  },
  {
    id: "copol-day2-05",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "11:00",
    endTime: "12:00",
    title: "Renata Longo – Odontopediatria",
    speaker: "Renata Longo",
    location: "Auditório Principal",
    description: "Renata Longo – Odontopediatria",
    type: "Palestra",
    order: 18,
  },
  {
    id: "copol-day2-06",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "12:00",
    endTime: "14:00",
    title: "Almoço",
    speaker: null,
    location: "Praça de Alimentação",
    description: "Almoço",
    type: "Intervalo",
    order: 19,
  },
  {
    id: "copol-day2-07",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "14:00",
    endTime: "15:00",
    title: "Hands On Radiotech",
    speaker: "Radiotech",
    location: "Sala Hands On 1",
    description: "Hands On Radiotech",
    type: "Hands On",
    order: 20,
  },
  {
    id: "copol-day2-08",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "15:00",
    endTime: "16:00",
    title: "Hands On Marcela – Diastema",
    speaker: "Marcela",
    location: "Sala Hands On 2",
    description: "Hands On Marcela – Diastema",
    type: "Hands On",
    order: 21,
  },
  {
    id: "copol-day2-09",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "15:30",
    endTime: "16:30",
    title: "Hands On Fotografia – Dra. Debora",
    speaker: "Dra. Debora",
    location: "Sala Hands On 3",
    description: "Hands On Fotografia – Dra. Debora",
    type: "Hands On",
    order: 22,
  },
  {
    id: "copol-day2-10",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "16:00",
    endTime: "17:00",
    title: "Hands On Angelus",
    speaker: "Angelus",
    location: "Sala Hands On 1",
    description: "Hands On Angelus",
    type: "Hands On",
    order: 23,
  },
  {
    id: "copol-day2-11",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "17:00",
    endTime: "18:00",
    title: "Hands On Integrale",
    speaker: "Integrale",
    location: "Sala Hands On 2",
    description: "Hands On Integrale",
    type: "Hands On",
    order: 24,
  },
  {
    id: "copol-day2-12",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "18:00",
    endTime: "19:00",
    title: "Coffee Break",
    speaker: null,
    location: "Área de Convivência",
    description: "Coffee Break",
    type: "Intervalo",
    order: 25,
  },
  {
    id: "copol-day2-13",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "19:00",
    endTime: "20:00",
    title: "Dr. Ricardo Navarro",
    speaker: "Dr. Ricardo Navarro",
    location: "Auditório Principal",
    description: "Dr. Ricardo Navarro",
    type: "Palestra",
    order: 26,
  },
  {
    id: "copol-day2-14",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "20:00",
    endTime: "21:00",
    title: "Dra. Gabriella Kayamori",
    speaker: "Dra. Gabriella Kayamori",
    location: "Auditório Principal",
    description: "Dra. Gabriella Kayamori",
    type: "Palestra",
    order: 27,
  },
  {
    id: "copol-day2-15",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "21:00",
    endTime: "22:00",
    title: "Encerramento com Coquetel Dia 2",
    speaker: null,
    location: "Área de Convivência",
    description: "Encerramento com Coquetel Dia 2",
    type: "Solenidade",
    order: 28,
  },

  // ==========================================
  // SÁBADO — 07/11/2026 (5 atividades)
  // ==========================================
  {
    id: "copol-day3-01",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "08:00",
    endTime: "09:30",
    title: "Abertura dos portões",
    speaker: null,
    location: "Entrada Principal",
    description: "Abertura dos portões",
    type: "Credenciamento",
    order: 29,
  },
  {
    id: "copol-day3-02",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "09:30",
    endTime: "10:00",
    title: "Coffee Break",
    speaker: null,
    location: "Área de Convivência",
    description: "Coffee Break",
    type: "Intervalo",
    order: 30,
  },
  {
    id: "copol-day3-03",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "10:00",
    endTime: "11:00",
    title: "Dra. Stephanie – Dentística",
    speaker: "Dra. Stephanie",
    location: "Auditório Principal",
    description: "Dra. Stephanie – Dentística",
    type: "Palestra",
    order: 31,
  },
  {
    id: "copol-day3-04",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "11:00",
    endTime: "12:00",
    title: "Joab Cabral – Estomatologia",
    speaker: "Joab Cabral",
    location: "Auditório Principal",
    description: "Joab Cabral – Estomatologia",
    type: "Palestra",
    order: 32,
  },
  {
    id: "copol-day3-05",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "12:00",
    endTime: "13:00",
    title: "Cerimônia de Encerramento",
    speaker: null,
    location: "Auditório Principal",
    description: "Cerimônia de Encerramento",
    type: "Solenidade",
    order: 33,
  },
];

/**
 * Retorna as 34 atividades oficiais adaptando o eventId se fornecido.
 */
export function getCopolFallbackSchedule(eventId?: string): ScheduleItem[] {
  if (!eventId) return COPOL_FALLBACK_SCHEDULE;
  return COPOL_FALLBACK_SCHEDULE.map((item) => ({
    ...item,
    eventId,
  }));
}
