import type { ScheduleItem } from "./api";

/**
 * Grade Oficial da Programação do COPOL 2026 (05/11 a 07/11).
 * Total de 27 atividades oficiais cadastradas rigorosamente conforme a grade oficial:
 * - 05/11 (Quinta-feira): 11 itens (incluindo sobreposição às 20:15–21:00)
 * - 06/11 (Sexta-feira): 11 itens (com "Tema a decidir", "inscrições em breve." e sem horário para Coquetel Dia 2)
 * - 07/11 (Sábado): 5 itens (com horários pontuais e sem horário para Cerimônia de Encerramento)
 *
 * Utilizado como fallback oficial de contingência e renderização estática.
 */
export const COPOL_FALLBACK_SCHEDULE: ScheduleItem[] = [
  // ==========================================
  // QUINTA-FEIRA — 05/11/2026 (11 atividades)
  // ==========================================
  {
    id: "copol-day1-01",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "08:30",
    endTime: "09:00",
    title: "Credenciamento – Retirada de Crachás",
    speaker: null,
    location: null,
    description: null,
    type: "Credenciamento",
    order: 0,
  },
  {
    id: "copol-day1-02",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "09:00",
    endTime: "10:00",
    title: "Cerimônia de Abertura – Coquetel de Boas-Vindas",
    speaker: null,
    location: null,
    description: null,
    type: "Solenidade",
    order: 1,
  },
  {
    id: "copol-day1-03",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "10:00",
    endTime: "11:00",
    title: "Cristina Miura – Lucratividade para Recém-Formados",
    speaker: "Cristina Miura",
    location: null,
    description: null,
    type: "Palestra",
    order: 2,
  },
  {
    id: "copol-day1-04",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "11:00",
    endTime: "12:00",
    title: "Prof. Dr. Letícia Lang – Odontologia Oncológica: o que o clínico precisa saber",
    speaker: "Prof. Dr. Letícia Lang",
    location: null,
    description: null,
    type: "Palestra",
    order: 3,
  },
  {
    id: "copol-day1-05",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "12:00",
    endTime: "14:00",
    title: "Almoço",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 4,
  },
  {
    id: "copol-day1-06",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "14:00",
    endTime: "18:00",
    title: "Hands On – inscrições em breve.",
    speaker: null,
    location: null,
    description: "inscrições em breve.",
    type: "Hands On",
    order: 5,
  },
  {
    id: "copol-day1-07",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "18:00",
    endTime: "19:00",
    title: "Coffee Break",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 6,
  },
  {
    id: "copol-day1-08",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "19:00",
    endTime: "19:15",
    title: "Credenciamento – Retirada de Crachás",
    speaker: null,
    location: null,
    description: null,
    type: "Credenciamento",
    order: 7,
  },
  {
    id: "copol-day1-09",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "19:15",
    endTime: "20:15",
    title: "Dra. Lázara – Palestra",
    speaker: "Dra. Lázara",
    location: null,
    description: null,
    type: "Palestra",
    order: 8,
  },
  {
    id: "copol-day1-10",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "20:15",
    endTime: "21:00",
    title: "Carlos Augusto – DTM",
    speaker: "Carlos Augusto",
    location: null,
    description: null,
    type: "Palestra",
    order: 9,
  },
  {
    id: "copol-day1-11",
    eventId: "copol-2026",
    date: "2026-11-05",
    startTime: "20:15",
    endTime: "21:00",
    title: "Coquetel de Encerramento Dia 1",
    speaker: null,
    location: null,
    description: null,
    type: "Solenidade",
    order: 10,
  },

  // ==========================================
  // SEXTA-FEIRA — 06/11/2026 (11 atividades)
  // ==========================================
  {
    id: "copol-day2-01",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "08:00",
    endTime: "08:30",
    title: "Recepção com DJ",
    speaker: null,
    location: null,
    description: null,
    type: "Recepção",
    order: 0,
  },
  {
    id: "copol-day2-02",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "08:30",
    endTime: "09:30",
    title: "Franciele Covalti – Tema a decidir",
    speaker: "Franciele Covalti",
    location: null,
    description: "Tema a decidir",
    type: "Palestra",
    order: 1,
  },
  {
    id: "copol-day2-03",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "09:30",
    endTime: "10:00",
    title: "Coffee Break",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 2,
  },
  {
    id: "copol-day2-04",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "10:00",
    endTime: "11:00",
    title: "Dr. Giuliano Cesar – Periodontia",
    speaker: "Dr. Giuliano Cesar",
    location: null,
    description: null,
    type: "Palestra",
    order: 3,
  },
  {
    id: "copol-day2-05",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "11:00",
    endTime: "12:00",
    title: "Renata Longo – Odontopediatria",
    speaker: "Renata Longo",
    location: null,
    description: null,
    type: "Palestra",
    order: 4,
  },
  {
    id: "copol-day2-06",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "12:00",
    endTime: "14:00",
    title: "Almoço",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 5,
  },
  {
    id: "copol-day2-07",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "14:00",
    endTime: "18:00",
    title: "Hands On – inscrições em breve.",
    speaker: null,
    location: null,
    description: "inscrições em breve.",
    type: "Hands On",
    order: 6,
  },
  {
    id: "copol-day2-08",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "18:00",
    endTime: "19:00",
    title: "Coffee Break",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 7,
  },
  {
    id: "copol-day2-09",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "19:00",
    endTime: "20:00",
    title: "Dr. Ricardo Navarro",
    speaker: "Dr. Ricardo Navarro",
    location: null,
    description: null,
    type: "Palestra",
    order: 8,
  },
  {
    id: "copol-day2-10",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: "20:00",
    endTime: "21:00",
    title: "Dra. Gabriella Kayamori",
    speaker: "Dra. Gabriella Kayamori",
    location: null,
    description: null,
    type: "Palestra",
    order: 9,
  },
  {
    id: "copol-day2-11",
    eventId: "copol-2026",
    date: "2026-11-06",
    startTime: null,
    endTime: null,
    title: "Coquetel de Encerramento Dia 2",
    speaker: null,
    location: null,
    description: null,
    type: "Solenidade",
    order: 10,
  },

  // ==========================================
  // SÁBADO — 07/11/2026 (5 atividades)
  // ==========================================
  {
    id: "copol-day3-01",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "08:00",
    endTime: null,
    title: "Nikolas Barros",
    speaker: "Nikolas Barros",
    location: null,
    description: null,
    type: "Palestra",
    order: 0,
  },
  {
    id: "copol-day3-02",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "09:30",
    endTime: null,
    title: "Coffee Break",
    speaker: null,
    location: null,
    description: null,
    type: "Intervalo",
    order: 1,
  },
  {
    id: "copol-day3-03",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "10:00",
    endTime: null,
    title: "Dra. Stephanie – Dentística",
    speaker: "Dra. Stephanie",
    location: null,
    description: null,
    type: "Palestra",
    order: 2,
  },
  {
    id: "copol-day3-04",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: "11:00",
    endTime: null,
    title: "Joab Cabral – Estomatologia",
    speaker: "Joab Cabral",
    location: null,
    description: null,
    type: "Palestra",
    order: 3,
  },
  {
    id: "copol-day3-05",
    eventId: "copol-2026",
    date: "2026-11-07",
    startTime: null,
    endTime: null,
    title: "Cerimônia de Encerramento",
    speaker: null,
    location: null,
    description: null,
    type: "Solenidade",
    order: 4,
  },
];

/**
 * Retorna as 27 atividades oficiais adaptando o eventId se fornecido.
 */
export function getCopolFallbackSchedule(eventId?: string): ScheduleItem[] {
  if (!eventId) return COPOL_FALLBACK_SCHEDULE;
  return COPOL_FALLBACK_SCHEDULE.map((item) => ({
    ...item,
    eventId,
  }));
}
