plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.elginprinter'
version = '0.1.0'

android {
  namespace "expo.modules.elginprinter"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  maven { url "https://www.jitpack.io" }
}

dependencies {
  implementation("com.github.iminsoftware:IminPrinterLibrary:V2.0.0.18")
  implementation files('libs/iminPrinterSDK-15_V1.3.2_2505261539.jar')
  implementation("io.reactivex.rxjava2:rxandroid:2.0.1")
  implementation("io.reactivex.rxjava2:rxjava:2.1.8")
  implementation("com.github.bumptech.glide:glide:4.16.0")
}
